name: CI

on:
  push:
    branches: [ main ]
    tags-ignore: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [3.4, 4.0, 4.1, 4.2, 5.0]

    container:
      image: redmine:${{ matrix.version }}
      env:
        REDMINE_HOME: /usr/src/redmine
        RAILS_ENV: test

    steps:
    - uses: actions/checkout@v3
    - name: Install essential
      run: apt-get update && apt-get install -y build-essential
    - name: Create database.yml
      run: |
        cat > ${REDMINE_HOME}/config/database.yml <<EOF
        test:
          adapter: "sqlite3"
          host: "localhost"
          username: "redmine"
          database: "sqlite/redmine.db"
          encoding: "utf8"
        EOF
    - name: Setup environments
      run: |
        PLUGIN_DIR=`pwd`
        PLUGIN_NAME=`basename ${PLUGIN_DIR}`
        cd ${REDMINE_HOME}/plugins
        ln -s ${PLUGIN_DIR} ${PLUGIN_NAME}
        cd ..
        bundle install --with test
        bundle exec rake db:drop db:create db:migrate redmine:plugins:migrate
        echo ja | bundle exec rake redmine:load_default_data
    - name: Run tests
      run: |
        cd ${REDMINE_HOME}
        bundle exec rake redmine:plugins:test NAME=redmine_changeset_relation
